// ============================================================
// Auth Callback Route (T0.4)
// Handles all Supabase email redirect flows:
//
//   1. token_hash flow  — default Supabase email links (OTP-based).
//      Works cross-browser, cross-device, and in email preview panes
//      because it does NOT require the PKCE code_verifier cookie.
//
//   2. code flow        — PKCE-based, generated by signInWithOAuth or
//      signUp() when redirectTo is provided. Requires same-browser session.
//
// The route uses NEXT_PUBLIC_SITE_URL (resolved in next.config.ts for every
// environment: production, preview, and local dev) so redirects always land
// on the correct domain.
// ============================================================

import { type EmailOtpType } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { ensureProfileForUser } from "@/lib/auth/session";

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;

  const tokenHash = searchParams.get("token_hash");
  const type = searchParams.get("type") as EmailOtpType | null;
  const code = searchParams.get("code");
  const rawNext = searchParams.get("next") ?? "/dashboard";
  const errorParam = searchParams.get("error");
  const errorDescription = searchParams.get("error_description");

  // Use the resolved site URL so every deployment redirects to its own origin.
  // Falls back to request.nextUrl.origin only if the env var is missing.
  const origin =
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ??
    request.nextUrl.origin;

  // Only allow internal redirects — strip any absolute/external paths
  const next = rawNext.startsWith("/") ? rawNext : "/dashboard";

  // ── Supabase returned an error in the query string ────────────────────────
  // This happens when the link has already been used, expired, or the email
  // client pre-fetched it. Rather than crash, redirect gracefully.
  if (errorParam) {
    const msg = errorDescription ?? errorParam;
    console.warn("[auth/callback] Supabase returned error:", msg);
    return NextResponse.redirect(
      `${origin}/login?error=${encodeURIComponent(msg)}`
    );
  }

  const supabase = await createClient();

  // ── Path 1: token_hash (OTP) flow ────────────────────────────────────────
  // This is the modern, recommended flow. Supabase sends:
  //   ?token_hash=<hash>&type=<email|signup|recovery|...>
  // It does NOT need the PKCE code_verifier cookie, so it works everywhere.
  if (tokenHash && type) {
    const { data, error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type,
    });

    if (!error && data.session && data.user) {
      await ensureProfileForUser(supabase, data.user);
      return NextResponse.redirect(`${origin}${next}`);
    }

    console.warn("[auth/callback] verifyOtp failed:", error?.message);
    return NextResponse.redirect(
      `${origin}/login?error=${encodeURIComponent(error?.message ?? "otp_failed")}`
    );
  }

  // ── Path 2: code (PKCE) flow ─────────────────────────────────────────────
  // Used by OAuth providers and signUp() with redirectTo. Requires the
  // code_verifier cookie to be present (same browser session).
  if (code) {
    const { data, error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error && data.session && data.user) {
      await ensureProfileForUser(supabase, data.user);
      return NextResponse.redirect(`${origin}${next}`);
    }

    console.warn("[auth/callback] exchangeCodeForSession failed:", error?.message);
    return NextResponse.redirect(
      `${origin}/login?error=${encodeURIComponent(error?.message ?? "exchange_failed")}`
    );
  }

  // ── No recognised parameters ─────────────────────────────────────────────
  console.warn("[auth/callback] No token_hash or code in request.");
  return NextResponse.redirect(`${origin}/login?error=missing_token`);
}
